### ISSUE TITLE
stringify() writes separator on the front of the next chunk

### ISSUE THREAD

**Issue by raine** [dominictarr/JSONStream#70]
Hey,

Is there a particular reason why stringify writes the separator in front of the chunks instead of in the end as the chunks are emitted? [link](https://github.com/dominictarr/JSONStream/blob/1e35abcd6f4909d6dbb17c1171cd49bff88b41cd/index.js#L149-L150)

```js
if(first) { first = false ; stream.queue(op + json)}
else stream.queue(sep + json)
                  ^^^
```

I'm asking because I have an issue where if I pipe stringified JSON to `bunyan-cli`, it won't process the latest line of JSON until it gets the new line separator from the next chunk. Apparently it doesn't consider the line of JSON complete until it gets the line break.

```diff
-    if(first) { first = false ; stream.queue(op + json)}
-    else stream.queue(sep + json)
+    if(first) { first = false ; stream.queue(op + json + sep)}
+    else stream.queue(json + sep)
```

Changing the code like this fixes the issue but might break other things. Any thoughts?

**Comment by Poetro** [comment]
Because you don't know, what will be the last, and you cannot remove already sent characters.
So in the first chunk, there is no reparator, but there are one before every other. For example, you want to construct an array of objects. But you don't know when that stream will end, so you write out `,` before each except the last, so you don't have a trailing comma, as that is not valid JSON.

**Comment by raine** [comment]
@Poetro, yep, I actually wrote my own stringifying logic as I realized it's simple because the use case doesn't require wrapping the stream in an array, and therefore can always send a line break after an object.
